# Generated by Django 3.0.5 on 2021-04-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ManyToManyField(blank=True, help_text='Выберите категорию', null=True, related_name='titles', to='api.Category', verbose_name='Категория'),
        ),
    ]
